import { DataGridProperty } from "templates/dataGrid/DataGridProperty";
import { dataGridCommonData } from "templates/dataGrid/objects/common/DataGridCommonData";
import { dataGridCustomData } from "templates/dataGrid/objects/common/DataGridCustomData";
import { dataGridExtensionAny } from "templates/dataGrid/objects/common/DataGridExtensionAny";
import { dataGridExtensionNameValue } from "templates/dataGrid/objects/common/DataGridExtensionNameValue";
import { dataGridBitRecordProperties } from "templates/dataGrid/objects/common/properties/DataGridBitRecordProperties";
import { dataGridNameTagProperties } from "templates/dataGrid/objects/common/properties/DataGridNameTagProperties";
import { dataGridSensorProperties } from "templates/dataGrid/objects/common/properties/DataGridSensorProperties";
import { dataGridUomProperties } from "templates/dataGrid/objects/common/properties/DataGridUomProperties";

export const dataGridTubular: DataGridProperty = {
  name: "tubulars",
  documentation: "",
  isContainer: true,
  properties: [
    {
      name: "xmlns",
      documentation: "",
      isAttribute: true
    },
    {
      name: "version",
      documentation: "",
      isAttribute: true
    },
    {
      name: "tubular",
      documentation:
        'A single tubular (assembly). This represents the "transient" assemblies used in drilling a well as opposedto the "fixed" assemblies (see wbGeometry).',
      isMultiple: true,
      isContainer: true,
      properties: [
        {
          name: "uidWell",
          documentation:
            "Unique identifier for the well. This uniquely represents the well referenced by the (possibly non-unique) nameWell.",
          isAttribute: true
        },
        {
          name: "uidWellbore",
          documentation:
            "Unique identifier for the wellbore. This uniquely represents the wellbore referenced by the (possibly non-unique) nameWellbore.",
          isAttribute: true
        },
        {
          name: "uid",
          documentation: "Unique identifier for the tubular (assembly).",
          isAttribute: true
        },
        {
          name: "nameWell",
          documentation: ""
        },
        {
          name: "nameWellbore",
          documentation:
            "Human recognizable context for the wellbore that contains the tubular."
        },
        {
          name: "name",
          documentation:
            "Human recognizable context for the tubular (assembly)."
        },
        {
          name: "typeTubularAssy",
          documentation: "Type of tubular assembly."
        },
        {
          name: "valveFloat",
          documentation:
            'Is float valve present? Values are "true" (or "1") and "false" (or "0").'
        },
        {
          name: "sourceNuclear",
          documentation:
            'Is nuclear tool present? Values are "true" (or "1") and "false" (or "0").'
        },
        {
          name: "diaHoleAssy",
          documentation: "Maximum hole size generated by assembly.",
          properties: dataGridUomProperties
        },
        {
          name: "tubularComponent",
          documentation:
            "Container element for the tubular component elements.",
          isContainer: true,
          isMultiple: true,
          properties: [
            {
              name: "uid",
              documentation: "Unique identifier for the component.",
              isAttribute: true
            },
            {
              name: "typeTubularComp",
              documentation: "Type of component."
            },
            {
              name: "sequence",
              documentation:
                "The sequence within which the components entered the hole. That is, a sequence number of 1 entered first, 2 entered next, etc."
            },
            {
              name: "description",
              documentation: "Description of item and details."
            },
            {
              name: "id",
              documentation: "Internal diameter of object.",
              properties: dataGridUomProperties
            },
            {
              name: "od",
              documentation: "Outside diameter of the body of the item.",
              properties: dataGridUomProperties
            },
            {
              name: "odMx",
              documentation: "Maximum outside diameter.",
              properties: dataGridUomProperties
            },
            {
              name: "len",
              documentation: "Length of the item.",
              properties: dataGridUomProperties
            },
            {
              name: "lenJointAv",
              documentation: "Average length of joint for tubulars.",
              properties: dataGridUomProperties
            },
            {
              name: "numJointStand",
              documentation: "Number of joints per stand of tubular."
            },
            {
              name: "wtPerLen",
              documentation: "Weight per unit length.",
              properties: dataGridUomProperties
            },
            {
              name: "grade",
              documentation: "Material grade for the tubular section."
            },
            {
              name: "odDrift",
              documentation: "Minimum pass through diameter.",
              properties: dataGridUomProperties
            },
            {
              name: "tensYield",
              documentation: "Yield stress of steel - worn stress.",
              properties: dataGridUomProperties
            },
            {
              name: "tqYield",
              documentation: "Torque at which yield occurs.",
              properties: dataGridUomProperties
            },
            {
              name: "stressFatig",
              documentation: "Fatigue endurance limit.",
              properties: dataGridUomProperties
            },
            {
              name: "lenFishneck",
              documentation: "Fish neck length.",
              properties: dataGridUomProperties
            },
            {
              name: "idFishneck",
              documentation: "Fish neck inside diameter.",
              properties: dataGridUomProperties
            },
            {
              name: "odFishneck",
              documentation: "Fish neck outside diameter.",
              properties: dataGridUomProperties
            },
            {
              name: "disp",
              documentation: "Closed end displacement.",
              properties: dataGridUomProperties
            },
            {
              name: "presBurst",
              documentation: "Burst pressure.",
              properties: dataGridUomProperties
            },
            {
              name: "presCollapse",
              documentation: "Collapse pressure.",
              properties: dataGridUomProperties
            },
            {
              name: "classService",
              documentation: "Service class."
            },
            {
              name: "wearWall",
              documentation: "Wall thickness wear (commonly in percent).",
              properties: dataGridUomProperties
            },
            {
              name: "thickWall",
              documentation: "Wall thickness.",
              properties: dataGridUomProperties
            },
            {
              name: "configCon",
              documentation: "Box/Pin configuration."
            },
            {
              name: "bendStiffness",
              documentation: "Bending stiffness of tubular.",
              properties: dataGridUomProperties
            },
            {
              name: "axialStiffness",
              documentation: "Axial stiffness of tubular.",
              properties: dataGridUomProperties
            },
            {
              name: "torsionalStiffness",
              documentation: "Torsional stiffness of tubular.",
              properties: dataGridUomProperties
            },
            {
              name: "typeMaterial",
              documentation: "Type of material."
            },
            {
              name: "doglegMx",
              documentation: "Maximum dogleg severity.",
              properties: dataGridUomProperties
            },
            {
              name: "vendor",
              documentation: "Name of vendor."
            },
            {
              name: "model",
              documentation: "Component name from manufacturer."
            },
            {
              name: "nameTag",
              documentation:
                "An identification tag for the component tool. A serial number is a type of identification tag however some tags contain many pieces of information. This structure just identifies the tag and does not describe the contents.",
              properties: dataGridNameTagProperties
            },
            {
              name: "bitRecord",
              documentation: "Bit object.",
              isContainer: true,
              properties: dataGridBitRecordProperties
            },
            {
              name: "areaNozzleFlow",
              documentation: "Total area of nozzles.",
              properties: dataGridUomProperties
            },
            {
              name: "nozzle",
              documentation:
                "Set of nozzle objects. Examples of items that have nozzles are bit, hole opener, circulation sub, jetting sub, pressure relief sub.",
              isContainer: true,
              isMultiple: true,
              properties: [
                {
                  name: "uid",
                  documentation: "Unique identifier for the nozzle.",
                  isAttribute: true
                },
                {
                  name: "index",
                  documentation: "Index if this is an indexed object."
                },
                {
                  name: "diaNozzle",
                  documentation: "Nozzle diameter.",
                  properties: dataGridUomProperties
                },
                {
                  name: "typeNozzle",
                  documentation: "Nozzle type."
                },
                {
                  name: "len",
                  documentation: "Length of the nozzle.",
                  properties: dataGridUomProperties
                },
                {
                  name: "orientation",
                  documentation: "Nozzle orientation."
                },
                dataGridCustomData,
                dataGridExtensionAny,
                dataGridExtensionNameValue
              ]
            },
            {
              name: "connection",
              documentation: "Connection object.",
              isContainer: true,
              isMultiple: true,
              properties: [
                {
                  name: "uid",
                  documentation: "Unique identifier for the connection.",
                  isAttribute: true
                },
                {
                  name: "id",
                  documentation: "Internal diameter of object.",
                  properties: dataGridUomProperties
                },
                {
                  name: "od",
                  documentation: "Outside diameter of the body of the item.",
                  properties: dataGridUomProperties
                },
                {
                  name: "len",
                  documentation: "Length of the item.",
                  properties: dataGridUomProperties
                },
                {
                  name: "typeThread",
                  documentation: "Thread type from API RP7G, 5CT."
                },
                {
                  name: "sizeThread",
                  documentation: "Thread size.",
                  properties: dataGridUomProperties
                },
                {
                  name: "tensYield",
                  documentation: "Yield stress of steel - worn stress.",
                  properties: dataGridUomProperties
                },
                {
                  name: "tqYield",
                  documentation: "Torque at which yield occurs.",
                  properties: dataGridUomProperties
                },
                {
                  name: "position",
                  documentation: "Where connected."
                },
                {
                  name: "criticalCrossSection",
                  documentation: "For bending stiffness ratio.",
                  properties: dataGridUomProperties
                },
                {
                  name: "presLeak",
                  documentation: "Leak pressure rating.",
                  properties: dataGridUomProperties
                },
                {
                  name: "tqMakeup",
                  documentation: "Make up torque.",
                  properties: dataGridUomProperties
                },
                dataGridCustomData,
                dataGridExtensionAny,
                dataGridExtensionNameValue
              ]
            },
            {
              name: "jar",
              documentation: "Jar object.",
              isContainer: true,
              properties: [
                {
                  name: "forUpSet",
                  documentation: "Up set force.",
                  properties: dataGridUomProperties
                },
                {
                  name: "forDownSet",
                  documentation: "Down set force.",
                  properties: dataGridUomProperties
                },
                {
                  name: "forUpTrip",
                  documentation: "Up trip force.",
                  properties: dataGridUomProperties
                },
                {
                  name: "forDownTrip",
                  documentation: "Down trip force.",
                  properties: dataGridUomProperties
                },
                {
                  name: "forPmpOpen",
                  documentation: "Pump open force.",
                  properties: dataGridUomProperties
                },
                {
                  name: "forSealFric",
                  documentation: "Seal friction force.",
                  properties: dataGridUomProperties
                },
                {
                  name: "typeJar",
                  documentation: "The kind of jar."
                },
                {
                  name: "jarAction",
                  documentation: "The jar action."
                },
                dataGridCustomData,
                dataGridExtensionAny
              ]
            },
            {
              name: "mwdTool",
              documentation: "MWD (measurement while drilling) tool object.",
              isContainer: true,
              properties: [
                {
                  name: "flowrateMn",
                  documentation: "Minimum flow rate.",
                  properties: dataGridUomProperties
                },
                {
                  name: "flowrateMx",
                  documentation: "Maximum flow rate.",
                  properties: dataGridUomProperties
                },
                {
                  name: "tempMx",
                  documentation: "Maximum Temperature.",
                  properties: dataGridUomProperties
                },
                {
                  name: "idEquv",
                  documentation: "Equivalent inner diameter.",
                  properties: dataGridUomProperties
                },
                {
                  name: "sensor",
                  documentation: "Sensor object.",
                  isContainer: true,
                  isMultiple: true,
                  properties: dataGridSensorProperties
                },
                dataGridCustomData,
                dataGridExtensionAny
              ]
            },
            {
              name: "motor",
              documentation: "Motor object.",
              isContainer: true,
              properties: [
                {
                  name: "offsetTool",
                  documentation: "Tool offset from bottom.",
                  properties: dataGridUomProperties
                },
                {
                  name: "presLossFact",
                  documentation: "Pressure loss factor."
                },
                {
                  name: "flowrateMn",
                  documentation: "Minimum flow rate.",
                  properties: dataGridUomProperties
                },
                {
                  name: "flowrateMx",
                  documentation: "Maximum flow rate.",
                  properties: dataGridUomProperties
                },
                {
                  name: "diaRotorNozzle",
                  documentation: "Diameter of rotor at nozzle.",
                  properties: dataGridUomProperties
                },
                {
                  name: "clearanceBearBox",
                  documentation: "Clearance inside bearing box.",
                  properties: dataGridUomProperties
                },
                {
                  name: "lobesRotor",
                  documentation: "Number of rotor lobes."
                },
                {
                  name: "lobesStator",
                  documentation: "Number of stator lobes."
                },
                {
                  name: "typeBearing",
                  documentation: "Type of bearing. "
                },
                {
                  name: "tempOpMx",
                  documentation: "Maximum operating temperature.",
                  properties: dataGridUomProperties
                },
                {
                  name: "rotorCatcher",
                  documentation:
                    'Is rotor catcher present? Values are "true" (or "1") and "false" (or "0").'
                },
                {
                  name: "dumpValve",
                  documentation:
                    'Is dump valve present? Values are "true" (or "1") and "false" (or "0").'
                },
                {
                  name: "diaNozzle",
                  documentation: "Nozzle diameter.",
                  properties: dataGridUomProperties
                },
                {
                  name: "rotatable",
                  documentation:
                    'Is motor rotatable? Values are "true" (or "1") and "false" (or "0").'
                },
                {
                  name: "bendSettingsMn",
                  documentation: "Minimum bend angle setting.",
                  properties: dataGridUomProperties
                },
                {
                  name: "bendSettingsMx",
                  documentation: "Maximum bend angle setting.",
                  properties: dataGridUomProperties
                },
                dataGridCustomData,
                dataGridExtensionAny
              ]
            },
            {
              name: "stabilizer",
              documentation: "Stabilizer object.",
              isContainer: true,
              isMultiple: true,
              properties: [
                {
                  name: "uid",
                  documentation: "Unique identifier for the stabilizer.",
                  isAttribute: true
                },
                {
                  name: "lenBlade",
                  documentation: "Length of blade.",
                  properties: dataGridUomProperties
                },
                {
                  name: "lenBladeGauge",
                  documentation:
                    "Gauge Length of blade. That is, the length of the blade which measures at the odBladeMx.",
                  properties: dataGridUomProperties
                },
                {
                  name: "odBladeMx",
                  documentation: "Maximum outer diameter of blade.",
                  properties: dataGridUomProperties
                },
                {
                  name: "odBladeMn",
                  documentation: "Minimum outer diameter of blade.",
                  properties: dataGridUomProperties
                },
                {
                  name: "distBladeBot",
                  documentation:
                    "Distance of blade bottom from bottom of component.",
                  properties: dataGridUomProperties
                },
                {
                  name: "shapeBlade",
                  documentation: "Blade shape. "
                },
                {
                  name: "factFric",
                  documentation: "Friction factor."
                },
                {
                  name: "typeBlade",
                  documentation: "Blade type."
                },
                dataGridCustomData,
                dataGridExtensionAny,
                dataGridExtensionNameValue
              ]
            },
            {
              name: "bend",
              documentation: "Bend object.",
              isContainer: true,
              isMultiple: true,
              properties: [
                {
                  name: "uid",
                  documentation: "Unique identifier for the bend.",
                  isAttribute: true
                },
                {
                  name: "angle",
                  documentation: "Angle of the bend.",
                  properties: dataGridUomProperties
                },
                {
                  name: "distBendBot",
                  documentation: "Distance of bend from bottom of component.",
                  properties: dataGridUomProperties
                },
                dataGridCustomData,
                dataGridExtensionAny,
                dataGridExtensionNameValue
              ]
            },
            {
              name: "holeOpener",
              documentation: "Hole opener object.",
              isContainer: true,
              properties: [
                {
                  name: "typeHoleOpener",
                  documentation: "Under reamer or fixed blade."
                },
                {
                  name: "numCutter",
                  documentation: "Number of cutters."
                },
                {
                  name: "manufacturer",
                  documentation: "Manufacturer / supplier of the item."
                },
                {
                  name: "diaHoleOpener",
                  documentation: "Diameter of the reamer.",
                  properties: dataGridUomProperties
                },
                dataGridCustomData,
                dataGridExtensionAny
              ]
            },
            {
              name: "rotarySteerableTool",
              documentation: "Rotary Steerable Tool.",
              isContainer: true,
              properties: [
                {
                  name: "deflectionMethod",
                  documentation:
                    "Method used to direct the deviation of the trajectory: PointBit or PushBit."
                },
                {
                  name: "bendAngle",
                  documentation:
                    "Used with PointTheBit type RSS tools, describes the angle of the bit.",
                  properties: dataGridUomProperties
                },
                {
                  name: "bendOffset",
                  documentation: "Offset from bottom connection to bend.",
                  properties: dataGridUomProperties
                },
                {
                  name: "holeSizeMn",
                  documentation:
                    "Minimum size of hole in which the tool can operate.",
                  properties: dataGridUomProperties
                },
                {
                  name: "holeSizeMx",
                  documentation:
                    "Maximum size of hole in which the tool can operate.",
                  properties: dataGridUomProperties
                },
                {
                  name: "wobMx",
                  documentation: "Maximum weight on the bit.",
                  properties: dataGridUomProperties
                },
                {
                  name: "operatingSpeed",
                  documentation: "Suggested operating speed.",
                  properties: dataGridUomProperties
                },
                {
                  name: "speedMx",
                  documentation: "Maximum rotation speed.",
                  properties: dataGridUomProperties
                },
                {
                  name: "flowRateMn",
                  documentation: "Minimum flow rate for tool operation.",
                  properties: dataGridUomProperties
                },
                {
                  name: "flowRateMx",
                  documentation: "Maximum flow rate for tool operation.",
                  properties: dataGridUomProperties
                },
                {
                  name: "downLinkFlowRateMn",
                  documentation: "Minimum flow rate for programming tool.",
                  properties: dataGridUomProperties
                },
                {
                  name: "downLinkFlowRateMx",
                  documentation: "Maximum flow rate for programming tool.",
                  properties: dataGridUomProperties
                },
                {
                  name: "pressLossFact",
                  documentation: "Pressure drop across tool."
                },
                {
                  name: "padCount",
                  documentation: "The number of contact pads."
                },
                {
                  name: "padLen",
                  documentation: "Length of contact pad.",
                  properties: dataGridUomProperties
                },
                {
                  name: "padWidth",
                  documentation: "Width of contact pad.",
                  properties: dataGridUomProperties
                },
                {
                  name: "padOffset",
                  documentation:
                    "Offset from bottom of pad to bottom connector.",
                  properties: dataGridUomProperties
                },
                {
                  name: "openPadOd",
                  documentation:
                    "Outside diameter of tool when pads are activated.",
                  properties: dataGridUomProperties
                },
                {
                  name: "closePadOd",
                  documentation:
                    "Outiside diameter of tool when pads are closed.",
                  properties: dataGridUomProperties
                },
                {
                  name: "sensor",
                  documentation: "A sensor.",
                  isContainer: true,
                  isMultiple: true,
                  properties: dataGridSensorProperties
                },
                dataGridCustomData,
                dataGridExtensionAny
              ]
            },
            dataGridCustomData,
            dataGridExtensionAny,
            dataGridExtensionNameValue
          ]
        },

        dataGridCommonData,
        dataGridCustomData
      ]
    }
  ]
};
