export const lithologyTypes = [
  "alkali feldspar rhyolite",
  "alkali olivine basalt",
  "amphibolite",
  "andesite",
  "anhydrite",
  "anorthositic rock",
  "anthracite",
  "aplite",
  "arenite",
  "arkose",
  "basalt",
  "basanite",
  "bauxite",
  "bituminous coal",
  "blueschist metamorphic rock",
  "boninite",
  "breccia",
  "calcarenite",
  "calcilutite",
  "calcisiltite",
  "carbonate ooze",
  "carbonatite",
  "chalk",
  "chert",
  "clay",
  "claystone",
  "coal",
  "conglomerate",
  "dacite",
  "diabase",
  "diamictite",
  "diorite",
  "dioritoid",
  "doleritic rock",
  "dolomite",
  "dolomite, calcareous",
  "eclogite",
  "exotic alkaline rock",
  "extrusive rock (volcanic)",
  "feldspar",
  "feldspathic arenite",
  "fine grained igneous rock",
  "foid dioritoid",
  "foid gabbroid",
  "foid syenitoid",
  "foidite",
  "foiditoid",
  "foidolite",
  "foliated metamorphic rock",
  "fragmental igneous rock",
  "gabbro",
  "gabbroic rock",
  "gabbroid",
  "glauconite",
  "gneiss",
  "granite",
  "granodiorite",
  "granofels",
  "granulite",
  "gravel",
  "greenstone",
  "greenstones",
  "greywacke",
  "gumbo",
  "gypsum",
  "halite",
  "hornfels",
  "igneous",
  "igneous rock",
  "impact generated material",
  "impure dolomite",
  "impure limestone",
  "intrusive rock (plutonic)",
  "iron rich sedimentary rock",
  "kalsilitic and melilitic rocks",
  "komatiitic rock",
  "latitic rock",
  "lignite",
  "lime boundstone",
  "lime framestone",
  "lime grainstone",
  "lime mudstone",
  "lime packstone",
  "lime wackestone",
  "limestone",
  "limestone, argillaceous",
  "limestone, dolomitic",
  "limestone, sandy",
  "marble",
  "marl",
  "metamorphic rock",
  "metamorphic rocks",
  "mica schist",
  "migmatite",
  "monzogabbro",
  "mud",
  "mudstone",
  "mylonitic rock",
  "no description",
  "no sample",
  "ooze",
  "ophiolite",
  "organic bearing mudstone",
  "peat",
  "pegmatite",
  "peridotite",
  "phaneritic igneous rock",
  "phonolite",
  "phonolitoid",
  "phosphate",
  "phosphate rock",
  "phyllite",
  "porphyry",
  "potassium and magnesium salts",
  "pyroclastic breccia",
  "pyroclastic rock",
  "pyroxenite",
  "quartz arenite",
  "quartzite",
  "rhyolite",
  "rock salt",
  "salt",
  "sand",
  "sandstone",
  "sapropel",
  "schist",
  "serpentine",
  "serpentinite",
  "shale",
  "siliceous ooze",
  "silt",
  "siltstone",
  "skarn",
  "slate",
  "spilite",
  "syenite",
  "syenitoid",
  "sylvite",
  "tephrite",
  "tephritoid",
  "tholeiitic basalt",
  "tillite (diamictite)",
  "tonalite",
  "trachyte",
  "trachytic rock",
  "trachytoid",
  "travertine",
  "tuff",
  "tuffite",
  "ultrabasic",
  "undifferentiated",
  "wacke",
  "unknown"
];
