export const riskAffectedPersonnel = [
  "cementer",
  "company man",
  "contractor",
  "directional driller",
  "driller",
  "drilling engineer",
  "drilling superintendent",
  "drilling team",
  "facility engineer",
  "field service manager",
  "foreman",
  "general service supervisor",
  "geologist",
  "member",
  "mud engineer",
  "mud logger",
  "MWD or LWD engineer",
  "perform engineer",
  "petrophysicist",
  "production engineer",
  "remotely operated vehicle engineer",
  "safety manger",
  "sales engineer",
  "service supervisor",
  "technical support",
  "tool pusher",
  "wireline engineer"
].sort((a, b) => a.localeCompare(b));
