export const riskSubCategory = [
  "gas kick",
  "shallow water influx",
  "other influx or kicks",
  "loss circulation",
  "poor hole cleaning",
  "good hole cleaning at high ROP",
  "high mud weight",
  "special additives needed",
  "gumbo problems",
  "high ECD - rheology related",
  "excessive circulation",
  "performing a kill",
  "mud weight change",
  "excessive pipe cement scaling",
  "pit gain or loss",
  "mud stability problems",
  "shallow gas flow",
  "twist off",
  "stuck pipe",
  "wireline stuck in hole",
  "stick and slip",
  "vibration - axial",
  "vibration - torsional",
  "vibration - transverse",
  "vibration unknown or rough drilling",
  "uneven wear of BHA",
  "uneven wear of drillstring",
  "excessive torque",
  "excessive drag",
  "reaming greater than 2 hours",
  "washouts",
  "tight hole or overPull",
  "failed inspections or fatigue wear",
  "mechanical",
  "drilling greater than 1000 feet/day",
  "drilling greater than 2000 feet/day",
  "drilling less than 20 feet/day",
  "trips greater than 24 hours",
  "excessive time for BHA makeup",
  "waiting on decisions",
  "waiting on weather",
  "waiting on tools",
  "sloughing or packoffs",
  "ballooning",
  "fracture problems",
  "unstable zones",
  "formation integrity test",
  "leak-off test",
  "tectonics",
  "pore pressure",
  "breakouts",
  "bed parallel",
  "wellbore stability",
  "excessive doglegs",
  "sidetrack",
  "BHA change for directional",
  "wrong total flow area",
  "well collision - actual",
  "well collision - technical",
  "geosteering",
  "abnormal tendency changes",
  "resurveying",
  "in-field referencing (IFR) actions",
  "bit or BHA performance",
  "drilling optimization",
  "bit balling",
  "lost cones or broken cutters",
  "excessive bit wear or gauge",
  "low rate of bit penetration",
  "high rate of bit penetration",
  "downhole tool",
  "surface system",
  "motor or rotary steerable system failure",
  "topdrive failure",
  "hoisting equipment failure",
  "circulating equipment failure",
  "electrical system failure",
  "blow out preventer events",
  "surface instrumentation problems",
  "rig communications",
  "completion equipment failure",
  "miscellaneous rig equipment",
  "tool or equipment failure",
  "squeeze jobs",
  "casing surge losses",
  "stuck casing or completion",
  "shoe failures",
  "early cement setup",
  "casing collapse",
  "milling",
  "excessive casing wear or cuttings",
  "excessive formation damage or skin",
  "casing rotation or reciprocation rqd",
  "broaching",
  "completion or casing",
  "stratigraphy",
  "fishing",
  "junk in hole",
  "delay due to political unrest",
  "rig move",
  "gas hydrates",
  "pending analysis",
  "riser disconnect",
  "other",
  "personnel",
  "environmental",
  "automotive",
  "asset",
  "information",
  "time",
  "HSE"
].sort((a, b) => a.localeCompare(b));
