export const riskAffectedPersonnel = [
  "cementer",
  "contractor",
  "remotely operated vehicle engineer",
  "production engineer",
  "petrophysicist",
  "perform engineer",
  "MWD or LWD engineer",
  "mud logger",
  "mud engineer",
  "geologist",
  "general service supervisor",
  "foreman",
  "facility engineer",
  "drilling team",
  "drilling superintendent",
  "drilling engineer",
  "driller",
  "directional driller",
  "technical support",
  "service supervisor",
  "sales engineer",
  "safety manger",
  "tool pusher",
  "wireline engineer"
].sort((a, b) => a.localeCompare(b));
