export const tubularComponentTypes = [
  "non-magnetic stabilizer",
  "non-magnetic collar",
  "stabilizer",
  "adjustable kickoff",
  "accelerator",
  "rotary steering tool",
  "sub-bar catcher",
  "sub-bent",
  "bit core diamond",
  "bit core PDC",
  "bit diamond fixed cut",
  "bit insert roller cone",
  "bit mill tooth roller cone",
  "bit PDC fixed cutter",
  "sub-bit",
  "bridge plug",
  "bullnose",
  "bull plug",
  "sub-bumper",
  "casing",
  "casing cutter",
  "hanger casing subsea",
  "hanger casing surface",
  "casing head",
  "catch assembly",
  "sub-catcher",
  "sub-circulation",
  "coiled tubing in hole",
  "coiled tubing on coil",
  "drill pipe compressive",
  "sub-cone",
  "core barrel",
  "core orientation barrel",
  "sub-crossover",
  "casing crossover",
  "sub-dart",
  "die collar",
  "die collar LH",
  "directional guidance system",
  "drill collar",
  "drill pipe",
  "drill pipe LH",
  "drill stem test BHA",
  "drive pipe",
  "dual catch assembly",
  "extension bowl overshot",
  "extension sub-overshot",
  "float collar",
  "float shoe",
  "sub-float",
  "flow head",
  "guide shoe",
  "MWD hang off sub",
  "heavy weight drill pipe",
  "heavy weight drill pipe LH",
  "riser high pressure",
  "bit hole opener",
  "casing inflatable packer",
  "motor instrumented",
  "jar",
  "sub-jetting",
  "junk basket",
  "junk basket reverse circulation",
  "sub-junk",
  "kelly",
  "keyseat wiper tool",
  "landing float collar",
  "lead impression block",
  "liner",
  "hanger liner",
  "magnet",
  "riser marine",
  "mill dress",
  "mill flat bottom",
  "mill hollow",
  "mill polish",
  "mill section",
  "mill taper",
  "mill washover",
  "mill packer picker assembly",
  "millout extension",
  "multilateral hanger running tool",
  "hanger mud line",
  "motor",
  "mule shoe",
  "logging while drilling tool",
  "stabilizer near bit roller reamer",
  "stabilizer near bit",
  "stabilizer non-rotating",
  "sub-orienting",
  "other",
  "overshot",
  "overshot LH",
  "oversize lip guide overshot",
  "packer",
  "polished bore receptacle",
  "mill pilot",
  "pipe cutter",
  "ported stinger",
  "sub-ported",
  "prepacked screens",
  "sub-pressure relief",
  "riser production",
  "MWD pulser",
  "sub-pump out",
  "sub-restrictor",
  "packer retrieve TT squeeze",
  "reversing tool",
  "stabilizer string roller reamer",
  "packer RTTS",
  "running tool",
  "safety joint",
  "safety joint LH",
  "sub-saver",
  "scab liner bit guide",
  "scraper",
  "scratchers",
  "casing shoe screw-in",
  "sub-shock",
  "drill collar short",
  "sub-side entry",
  "slotted liner",
  "spear",
  "stage cement collar",
  "motor steerable",
  "packer storm valve RTTS",
  "stabilizer string",
  "surface pipe",
  "taper tap",
  "taper tap LH",
  "tubing-conveyed perforating gun",
  "thruster",
  "tieback polished bore receptacle",
  "tieback stinger",
  "tubing",
  "hanger tubing",
  "turbine",
  "bit under reamer",
  "stabilizer variable blade",
  "washover pipe",
  "mill watermelon",
  "whipstock",
  "whipstock anchor",
  "stabilizer turbo back",
  "stabilizer inline",
  "stabilizer steerable",
  "sub-stop",
  "sub-filter",
  "mill casing cutting",
  "reamer",
  "unknown"
].sort((a, b) => a.localeCompare(b));
