import { Icon } from "@equinor/eds-core-react";
import {
  accessible,
  account_circle as accountCircle,
  add,
  arrow_down as arrowDown,
  arrow_up as arrowUp,
  assignment,
  calendar,
  check,
  chevron_down as chevronDown,
  chevron_right as chevronRight,
  compare,
  copy,
  delete_to_trash as deleteToTrash,
  edit,
  folder_open as folderOpen,
  format_line_spacing as formatLine,
  info_circle as infoCircle,
  launch,
  more_vertical as moreVertical,
  paste,
  refresh,
  settings,
  trending_up as isActive,
  world,
  filter_alt as filter,
  save,
  close,
  cloud_download as cloudDownload,
  person,
  new_alert as alert,
  filter_alt_active as activeFilter,
  done
} from "@equinor/eds-icons";
const icons = {
  accountCircle,
  chevronRight,
  chevronDown,
  isActive,
  launch,
  formatLine,
  refresh,
  paste,
  add,
  settings,
  accessible,
  check,
  copy,
  edit,
  folderOpen,
  deleteToTrash,
  moreVertical,
  assignment,
  infoCircle,
  compare,
  world,
  arrowUp,
  arrowDown,
  calendar,
  filter,
  save,
  close,
  cloudDownload,
  person,
  alert,
  activeFilter,
  done
};

Icon.add(icons);

export default Icon;
