import { Icon } from "@equinor/eds-core-react";
import {
  accessible,
  account_circle as accountCircle,
  filter_alt_active as activeFilter,
  add,
  arrow_down as arrowDown,
  arrow_drop_right as arrowDropRight,
  arrow_up as arrowUp,
  assignment,
  beat,
  calendar,
  check,
  chevron_down as chevronDown,
  chevron_right as chevronRight,
  chevron_up as chevronUp,
  clear,
  cloud_download as cloudDownload,
  cloud_off as cloudOff,
  compare,
  copy,
  delete_to_trash as deleteToTrash,
  done,
  edit,
  filter_alt as filter,
  folder_open as folderOpen,
  format_line_spacing as formatLine,
  info_circle as infoCircle,
  trending_up as isActive,
  launch,
  more_vertical as moreVertical,
  paste,
  person,
  refresh,
  save,
  search,
  settings,
  upload,
  world
} from "@equinor/eds-icons";
const icons = {
  accessible,
  accountCircle,
  activeFilter,
  add,
  arrowDown,
  arrowDropRight,
  arrowUp,
  assignment,
  beat,
  calendar,
  check,
  chevronDown,
  chevronRight,
  chevronUp,
  clear,
  cloudDownload,
  cloudOff,
  compare,
  copy,
  deleteToTrash,
  done,
  edit,
  filter,
  folderOpen,
  formatLine,
  infoCircle,
  isActive,
  launch,
  moreVertical,
  paste,
  person,
  refresh,
  save,
  search,
  settings,
  upload,
  world
};

Icon.add(icons);

export default Icon;
