export enum WellboreObjects {
  Well = "Well",
  Wellbore = "Wellbore",
  bhaRun = "bhaRun",
  log = "log",
  cementJobs = "cementJobs",
  message = "message",
  mudLog = "mudLog",
  trajectory = "trajectory",
  tubular = "tubular",
  wbGeometry = "wbGeometry",
  attachment = "attachment",
  convCore = "convCore",
  customObjcts = "customObjcts",
  drillReport = "drillReport",
  formationMarker = "formationMarker",
  mnemonicSet = "mnemonicSet",
  objectGroup = "objectGroup",
  opsReport = "opsReport",
  pressureTestPlan = "pressureTestPlan",
  rig = "rig",
  risk = "risk",
  sidewallCore = "sidewallCore",
  stimJob = "stimJob",
  surveyProgram = "surveyProgram",
  target = "target",
  toolErrorModel = "toolErrorModel",
  toolErrorTermSet = "toolErrorTermSet"
}

export enum DisabledWellObj {
  Well = "Well",
  Wellbore = "Wellbore",
  toolErrorTermSet = "toolErrorTermSet",
  toolErrorModel = "toolErrorModel",
  target = "target",
  surveyProgram = "surveyProgram",
  sidewallCore = "sidewallCore",
  stimJob = "stimJob",
  risk = "risk",
  rig = "rig",
  pressureTestPlan = "pressureTestPlan",
  opsReport = "opsReport",
  objectGroup = "objectGroup",
  mnemonicSet = "mnemonicSet",
  formationMarker = "formationMarker",
  drillReport = "drillReport",
  customObjcts = "customObjcts",
  convCore = "convCore",
  attachment = "attachment"
}
