export enum WellboreObjects {
  Well = "Well",
  Wellbore = "Wellbore",
  bhaRun = "bhaRun",
  changeLog = "changeLog",
  fluidsReport = "fluidsReport",
  formationMarker = "formationMarker",
  log = "log",
  message = "message",
  mudLog = "mudLog",
  risk = "risk",
  trajectory = "trajectory",
  tubular = "tubular",
  wbGeometry = "wbGeometry",
  attachment = "attachment",
  cementJobs = "cementJobs",
  convCore = "convCore",
  customObjcts = "customObjcts",
  drillReport = "drillReport",
  mnemonicSet = "mnemonicSet",
  objectGroup = "objectGroup",
  opsReport = "opsReport",
  pressureTestPlan = "pressureTestPlan",
  rig = "rig",
  sidewallCore = "sidewallCore",
  stimJob = "stimJob",
  surveyProgram = "surveyProgram",
  target = "target",
  toolErrorModel = "toolErrorModel",
  toolErrorTermSet = "toolErrorTermSet"
}

export enum EnabledWellboreObjects {
  bhaRun = "bhaRun",
  changeLog = "changeLog",
  fluidsReport = "fluidsReport",
  formationMarker = "formationMarker",
  log = "log",
  message = "message",
  mudLog = "mudLog",
  rig = "rig",
  risk = "risk",
  trajectory = "trajectory",
  tubular = "tubular",
  wbGeometry = "wbGeometry"
}
