version: '3.1'

services:
  mongo:
    image: mongo:4.4.1
    container_name: witsml-explorer-db
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db #Location for data folder can be changed.
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<insert username>
      - MONGO_INITDB_ROOT_PASSWORD=<insert password>
