name: Backend Build and Test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'Src/Witsml/**'
      - 'Src/WitsmlExplorer.Api/**'
      - 'Src/WitsmlExplorer.Console/**'
      - 'Tests/**'

permissions: {}

jobs:
  backend:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Build
        run: dotnet build /warnaserror --configuration Release
      - name: Test
        run: dotnet test --configuration Release --logger "console;verbosity=detailed"
