name: Backend Build and Test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'Src/Witsml/**'
      - 'Src/WitsmlExplorer.Api/**'
      - 'Src/WitsmlExplorer.Console/**'
      - 'Tests/**'

permissions: {}

jobs:
  backend:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Setup .NET 7
        uses: actions/setup-dotnet@a351d9ea84bc76ec7508debf02a39d88f8b6c0c0 # v2.1.1
        with:
          dotnet-version: 7.0.x
      - name: Build
        run: dotnet build /warnaserror --configuration Release
      - name: Test
        run: dotnet test --configuration Release --logger "console;verbosity=detailed"
